In [18]:
import torch
import numpy as np


In [6]:
device="cuda" if torch.cuda.is_available() else "cpu"
my_tensor=torch.tensor([[1,2,3],[4,5,6]],device=device)

print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor)

cuda:0
torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]], device='cuda:0')


In [13]:
x=torch.zeros(size=(3,3),dtype=torch.int64)
y=torch.rand(size=(2,3))
z=torch.eye(5,5)
print(x,y,z)

x=torch.linspace(start=0.1,end=1,steps=10)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]) tensor([[0.6753, 0.2061, 0.5653],
        [0.9765, 0.2301, 0.1660]]) tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [17]:
y=torch.arange(4)
print(y)
print(y.bool())
print(y.short())

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)


In [20]:
np_array=np.zeros((5,5))
tensor=torch.from_numpy(np_array)
tensor.short()

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int16)

## Tensor math and Comparison Operations

In [24]:
x=torch.tensor([1,2,3])
y=torch.tensor([3,4,5])
print(x+y)
print(torch.true_divide(x,y))

t=torch.zeros(3)
t.add_(x) #t+=x
print(t)

print(t**2)

tensor([4, 6, 8])
tensor([0.3333, 0.5000, 0.6000])
tensor([1., 2., 3.])
tensor([1., 4., 9.])


In [27]:
z=x>2
z

tensor([False, False,  True])

In [33]:
x1=torch.rand((2,5))
x2=torch.rand((5,3))

x3=torch.rand((2,2))

print(torch.mm(x1,x2)) #x1.mm(x2)

## Matrix Exponentiation
print(x3.matrix_power(2)) ## Square matrix


tensor([[1.1554, 2.2676, 1.1271],
        [0.5042, 1.9261, 1.4871]])
tensor([[0.6669, 0.9898],
        [0.3966, 0.5903]])


In [36]:
#Elementwise multiplication x*y
#sum
torch.dot(x,y)

tensor(26)